---
- name: Common setup for development environment
  hosts: localhost
  connection: local
  tasks:
    - name: Install dependencies with Homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - openssl
        - asdf

    - name: Ensure asdf is initialized in the shell
      lineinfile:
        path: ~/.zshrc
        line: |
          . $(brew --prefix asdf)/asdf.sh
        state: present

    - name: Ensure asdf completions are set up in the shell
      lineinfile:
        path: ~/.zshrc
        line: |
          fpath=($(brew --prefix asdf)/completions $fpath)
        state: present

