---
- name: Setup Vim for Rust development on macOS Sonoma
  hosts: localhost
  tasks:
    - name: Install Vim plugins
      block:
        - name: Ensure the Vim plugin directory exists
          file:
            path: "{{ lookup('env', 'HOME') }}/.vim/pack/plugins/start"
            state: directory

        - name: Install rust.vim plugin
          git:
            repo: 'https://github.com/rust-lang/rust.vim'
            dest: "{{ lookup('env', 'HOME') }}/.vim/pack/plugins/start/rust.vim"

        - name: Install coc.nvim plugin
          git:
            repo: 'https://github.com/neoclide/coc.nvim.git'
            dest: "{{ lookup('env', 'HOME') }}/.vim/pack/plugins/start/coc.nvim"
            version: 'release'

        - name: Install coc.nvim dependencies
          shell: |
            cd ~/.vim/pack/plugins/start/coc.nvim && npm install

        - name: Install gruvbox colorscheme
          git:
            repo: 'https://github.com/morhetz/gruvbox'
            dest: "{{ lookup('env', 'HOME') }}/.vim/pack/plugins/start/gruvbox"

    - name: Create coc-settings.json
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.vim/coc-settings.json"
        content: |
          {
            "rust-analyzer.cargo.loadOutDirsFromCheck": true,
            "rust-analyzer.procMacro.enable": true,
            "rust-analyzer.checkOnSave.command": "clippy",
            "rust-analyzer.checkOnSave.extraArgs": ["--", "-W", "clippy::pedantic"],
            "rust-analyzer.assist.importGranularity": "module",
            "rust-analyzer.assist.importPrefix": "by_crate",
            "rust-analyzer.completion.autoimport.enable": true,
            "suggest.floatConfig": {
              "maxWidth": 120,
              "maxHeight": 120
            },
            "rust-analyzer.lens.enable": true,
            "rust-analyzer.lens.methodReferences": true,
            "rust-analyzer.lens.references": true,
            "rust-analyzer.lens.debug": true,
            "rust-analyzer.inlayHints.enable": true,
            "rust-analyzer.inlayHints.typeHints": true,
            "rust-analyzer.inlayHints.parameterHints": true,
            "rust-analyzer.inlayHints.chainingHints": true,
            "rust-analyzer.inlayHints.returnHints": true
          }

    - name: Copy vimrc to user's home directory
      copy:
        src: vimrc
        dest: ~/.vimrc

